// <auto-generated />
using HotelSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelSystem.Data.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240110131528_HotelSystem")]
    partial class HotelSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelSystem.Model.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sheaton Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Helnan Hotel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tolip Hotel"
                        });
                });

            modelBuilder.Entity("HotelSystem.Model.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            Price = 200,
                            Specification = "Double Room Sea View"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 1,
                            Price = 150,
                            Specification = "Single Room Sea View"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 1,
                            Price = 179,
                            Specification = "Double Room City View"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 1,
                            Price = 120,
                            Specification = "Single Room City View"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 2,
                            Price = 100,
                            Specification = "Double Room Garden View"
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 2,
                            Price = 90,
                            Specification = "Single Room Garden View"
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 2,
                            Price = 120,
                            Specification = "Double Room Pool View"
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 2,
                            Price = 110,
                            Specification = "Single Room Pool View"
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 3,
                            Price = 80,
                            Specification = "Double Room Standard"
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 3,
                            Price = 70,
                            Specification = "Single Room Standard"
                        },
                        new
                        {
                            Id = 11,
                            HotelId = 3,
                            Price = 100,
                            Specification = "Double Room Deluxe"
                        },
                        new
                        {
                            Id = 12,
                            HotelId = 3,
                            Price = 95,
                            Specification = "Single Room Deluxe"
                        });
                });

            modelBuilder.Entity("HotelSystem.Model.Model.Room", b =>
                {
                    b.HasOne("HotelSystem.Model.Model.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelSystem.Model.Model.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
